name: 03 - Runners de workflow
on:
    workflow_dispatch:

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar SO
        shell: bash
        run: |
          echo "Este trabajo se ejecuta en un Runner de Ubuntu"
          echo $RUNNER_OS
  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Mostrar SO
        shell: bash
        run: |
          echo "Este trabajo se ejecuta en un Runner de Windows"
          echo $RUNNER_OS
  mac-echo:
    runs-on: macos-latest
    steps:
      - name: Mostrar SO
        shell: bash
        run: |
          echo "Este trabajo se ejecuta en un Runner MacOS"
          echo $RUNNER_OS
            
    