name: 04 - Uso de Actions
on:
    push:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Node Setup
        uses: actions/setup-node@v4
        with:
            node-version: '20.x'
      - name: Install Dependencies
        run: |
          cd my-app
          npm ci
      - name: Run Unit Tests
        run: |
          cd my-app
          npm run test
