name: 06 - Activity Typesç

on:
  pull_request:
    branches: 
        - develop
    types: [opened, synchronize]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name:
        run: echo "Running whenever a PR is opened or synchronized AND base branch is develop"