name: 07 - Contexts
run-name: 07 - Contexts | DEBUG - ${{ inputs.debug }}
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Debug mode'
        type: boolean
        default: false

env:
  MY_VAR: 'Hola Mundo'
  MY_WORKFLOW_VAR: 'workflow'
  MY_OVERWRITTEN_VAR: 'workflow'


jobs:     
  echo-data:
    env:
        MY_JOB_VAR: 'job'
        MY_OVERWRITTEN_VAR: 'job'
    runs-on: ubuntu-latest
    steps:
      - name: Show Info
        run: |
          echo "Nombre del evento: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Flujo de trabajo: ${{ github.workflow }}"
          echo "ID de ejecución: ${{ github.run_id }}"
          echo "Número de ejecución: ${{ github.run_number }}"

      - name: Retrieve Variable
        run: echo "${{ env.MY_VAR }}"

      - name: Print Env Variables
        run: |
          echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
          echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"

      - name: Print Env Variables by def
        run: |
          echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
          echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"

      
     
