name: 13 - Working with Outputs
on:
  workflow_dispatch:
      inputs:
        build-status:
            description: "Choose the build status for the demo"
            type: choice
            options: [success,failure]
            default: success

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outcome.status }}
    steps:
        - name: Print GITHUB_OUTPUT path
          run: echo "$GITHUB_OUTPUT.path"
        - name: Build
          id: build
          run: echo "status=${{ inputs.build-status}}" >> "$GITHUB_OUTPUT"

  deploy: 
    needs: build
    if: ${{ needs.build.outputs.build-status == 'success' }}  
    runs-on: ubuntu-latest
    steps:
        - name: Deploy
          run: "Deploying"

