name: 13 - Working with Outputs
on:
  workflow_dispatch:
      inputs:
        build-status:
            description: "Choose the build status for the demo"
            type: choice
            options: [success,failure]
            default: success

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
        build-status: ${{ steps.build.outputs.status }}
    steps:
        - name: Print GITHUB_OUTPUT path
          run: echo "${{ env.GITHUB_OUTPUT }}"
        - name: Build
          id: build
          run: echo "status=${{ inputs.build-status}}" >> "$GITHUB_OUTPUT"

  deploy: 
    needs: build
    if: ${{ needs.build.result == 'success' }}  
    #si la salida build-status del trabajo build es igual a success 
    runs-on: ubuntu-latest
    steps:
        - name: Deploy
          run: "Deploying"

