name:

on:
  workflow_dispatch:
      inputs:
        use-cache:
            description: "Whether to execute cache step"
            type: boolean
            default: true
        node-version:
            description: "Node version"
            type: choice
            options: [18.x, 20.x, 21.x]
            default: 20.x

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4
          - name: Setup Node
            uses: actions/setup-node@v4
            with:
                node-version: ${{ inputs.node-version }}

          - name: Download cached dependencies
            id: cache-deps
            if: ${{ inputs.use-cache == true }}
            uses: actions/cache@v3
            with:
              path: 14-caching/my-app/node_modules
              key: deps-node-modules-${{ hashFiles('14-caching/react-app/package-lock.json') }}

          - name: Install Dependencies
            if: steps.cache-deps.outputs.cache-hit != true
            run: |
              cd 14-caching/my-app
              npm ci
          - name: Run Unit Tests
            run: |
              cd 14-caching/my-app
              npm run test
          - name: Building
            run: |
              cd 14-caching/my-app
              npm run build
          - name: Deploying to nonprod
            run: echo "Deploying to nonprod"